import { BattleCharacter } from '../../features/battle/battle.model';

export const BATTLE_CHARACTERS: Record<
  string,
  Omit<BattleCharacter, 'isAlive' | 'position' | 'turnCount'>
> = {
  RAT: {
    id: 'char1',
    name: 'Celestial Guardian',
    race: 'rat',
    health: 85,
    maxHealth: 85,
    attack: 18,
    defense: 12,
    speed: 22,
    focus: 20,
    color: '#ff6b6b',
  },
  CAT: {
    id: 'char2',
    name: 'Blue Spider',
    race: 'cat',
    health: 90,
    maxHealth: 90,
    attack: 22,
    defense: 13,
    speed: 23,
    focus: 14,
    color: '#0000ff',
  },
  BEAR: {
    id: 'char3',
    name: 'Yellow Bear',
    race: 'bear',
    health: 130,
    maxHealth: 130,
    attack: 18,
    defense: 22,
    speed: 10,
    focus: 10,
    color: '#ffff00',
  },
  HORSE: {
    id: 'char4',
    name: 'White Horse',
    race: 'horse',
    health: 110,
    maxHealth: 110,
    attack: 21,
    defense: 14,
    speed: 20,
    focus: 10,
    color: '#ffffff',
  },
  GIRAFFE: {
    id: 'char5',
    name: 'Black Giraffe',
    race: 'giraffe',
    health: 95,
    maxHealth: 95,
    attack: 19,
    defense: 14,
    speed: 13,
    focus: 24,
    color: '#000000',
  },
};
