import { BattleCharacter } from '../../features/battle/battle.model';

export const BATTLE_CHARACTERS: Record<string, Omit<BattleCharacter, 'isAlive' | 'position'>> = {
  RAT: {
    id: 'char1',
    name: 'Celestial Guardian',
    health: 85,
    maxHealth: 85,
    attack: 18,
    defense: 12,
    speed: 22,
    focus: 20,
    color: '#ff6b6b',
  },
  CAT: {
    id: 'char2',
    name: 'Blue Spider',
    health: 85,
    maxHealth: 85,
    attack: 18,
    defense: 12,
    speed: 22,
    focus: 20,
    color: '#0000ff',
  },
  BEAR: {
    id: 'char3',
    name: 'Yellow Bear',
    health: 85,
    maxHealth: 85,
    attack: 18,
    defense: 12,
    speed: 22,
    focus: 20,
    color: '#ffff00',
  },
  HORSE: {
    id: 'char4',
    name: 'White Horse',
    health: 85,
    maxHealth: 85,
    attack: 18,
    defense: 12,
    speed: 22,
    focus: 20,
    color: '#ffffff',
  },
  GIRAFFE: {
    id: 'char5',
    name: 'Black Giraffe',
    health: 85,
    maxHealth: 85,
    attack: 18,
    defense: 12,
    speed: 22,
    focus: 20,
    color: '#000000',
  },
};
