export const SERVICE_PROVIDERS = [
  {
    id: 'acc062ef-6376-486c-a7d6-7ceb8466a9b4',
    type: 'INSURANCE',
    root: true,
    status: 'ACTIVE',
    name: 'Krüger + Co. AG - Degersheim',
    address: null,
    domain: null,
    email: 'michael.keller@ipex.ch',
    imageId: null,
  },
  {
    id: '30aa6123-ba52-4ca0-86d2-da805fe849b6',
    type: 'INSURANCE',
    root: true,
    status: 'ACTIVE',
    name: 'Krüger + Co. AG - Rothrist',
    address: null,
    domain: null,
    email: 'michael.keller@ipex.ch',
    imageId: null,
  },
  {
    id: 'ef373d1e-2095-4251-b86d-498717f7693b',
    type: 'INSURANCE',
    root: true,
    status: 'ACTIVE',
    name: 'Krüger + Co. AG - Grellingen',
    address: null,
    domain: null,
    email: null,
    imageId: null,
  },
  {
    id: 'e815d73f-9031-45b0-bfae-024c1ff8c621',
    type: 'INSURANCE',
    root: true,
    status: 'ACTIVE',
    name: 'Krüger + Co. AG - Münsingen',
    address: null,
    domain: null,
    email: null,
    imageId: null,
  },
];
